from . import test_order_workflow
from . import test_recruitment_pipeline
from . import test_product_suggestion
from . import test_stock_reports
from . import test_grade_transfer
from . import test_order_reassign
from . import test_delivery_trip
from . import test_damage_log
from . import test_delivery_drivers
from . import test_delivery_driver_dashboard
from . import test_fleet_integrity
from . import test_qweb_expressions
from . import test_dashboard_translations
from . import test_qweb_branch_chains
from . import test_warehouse_manager_sync
from . import test_warehouse_location_rules
from . import test_backend_auto_sync
from . import test_identity_registry
from . import test_qweb_handler_binding
from . import test_split_order_approval
from . import test_report_arabic
from . import test_admin_employee_create
from . import test_employee_dashboard_access
from . import test_qweb_owl_vocabulary
from . import test_sorting_plan
from . import test_damage_approval
from . import test_driver_document_review
from . import test_attendance_api_scope
from . import test_receiving_scope
from . import test_splash_screen
from . import test_dashboard_offer_display
